# build
FROM golang:1.20-buster AS build

WORKDIR /app


COPY ./ /app/
RUN go mod download

RUN go build -o /bank-holiday-be

# deploy
FROM gcr.io/distroless/base-debian11 AS deploy

WORKDIR /

COPY --from=build /bank-holiday-be /bank-holiday-be
COPY --from=build /app/data/holidays.json /data/holidays.json

USER nonroot:nonroot

ENTRYPOINT ["/bank-holiday-be"]
