name: nacho build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        default: info
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: bank-holidays
  PORT: 8080
  PROJECT_ID: nachobanana-d2b3a
  REGION: europe-west2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Google Cloud Provider
        uses: google-github-actions/auth@v1
        with:
          service_account: "github-actions@nachobanana-d2b3a.iam.gserviceaccount.com"
          credentials_json: "${{ secrets.CREDENTIALS_JSON }}"

      - name: Upload the application image to Container Registry
        run: gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}

      - name: Deploy the container image to Cloud Run
        run: |
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --image=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }} \
            --region=${{ env.REGION }} \
            --port=${{ env.PORT }} \
            --allow-unauthenticated

      - name: Build frontend for Firebase
        working-directory: ./app
        run: |
          APPLICATION_URL=$(
            gcloud run services describe ${{ env.IMAGE_NAME }} \
              --region=${{ env.REGION }} \
              --format="value(status.url)"
          )
          echo "VUE_APP_HOST_API=${APPLICATION_URL}" > ./.env
          echo "VUE_APP_PORT_API=443" >> ./.env
          npm ci
          npm run build

      - name: Deploy the frontend to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NACHOBANANA_D2B3A }}"
          projectId: ${{ env.PROJECT_ID }}
          channelId: live
