name: nacho build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        default: info
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: bank-holidays
  PORT: 8080
  PROJECT_ID: nachobanana-d2b3a
  REGION: europe-west2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Google Cloud Provider
        uses: google-github-actions/auth@v1
        with:
          service_account: "github-actions@nachobanana-d2b3a.iam.gserviceaccount.com"
          credentials_json: "${{ secrets.CREDENTIALS_JSON }}"

      - name: Check whether deployment already exists
        run: |
          [[ $(gcloud run services describe ${{ env.IMAGE_NAME }} --region=${{ env.REGION }}) ]] \
            && echo "DEPLOYMENT_EXISTS=true" >> ${GITHUB_ENV} \
            || echo "DEPLOYMENT_EXISTS=false" >> ${GITHUB_ENV}

      - name: Upload the application image to Container Registry
        if: ${{ env.DEPLOYMENT_EXISTS == "false" }}
        run: gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}

      - name: Deploy the container image to Cloud Run
        if: ${{ env.DEPLOYMENT_EXISTS == "false" }}
        run: |
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --image=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }} \
            --region=${{ env.REGION }} \
            --port=${{ env.PORT }} \
            --allow-unauthenticated

      - name: Change the `VUE_APP_HOST_API` and re-submit the image
        run: |
          APPLICATION_URL=$(
            gcloud run services describe ${{ env.IMAGE_NAME }} \
              --region=${{ env.REGION }} \
              --format="value(status.url)"
          )
          environment="VUE_APP_HOST_API=${APPLICATION_URL}\n"
          environment+="VUE_APP_PORT_API=443"
          echo "${environment}" > ./app/.env
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}

      - name: Deploy the updated container image to Cloud Run
        run: |
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --image=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }} \
            --region=${{ env.REGION }} \
            --port=${{ env.PORT }} \
            --allow-unauthenticated

      - name: Build frontend for Firebase
        working-directory: ./app
        run: |
          npm ci
          npm run build
          mv ./dist ../api/dist

      - name: Deploy the frontend to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NACHOBANANA_D2B3A }}"
          projectId: ${{ env.PROJECT_ID }}
          channelId: live
